Notification progress
home-assistant/companion.home-assistant pull request #1136
Opened 2024-11-10 22:56 UTC by EarMaster

Added support for progress notifications on Android.

https://developer.android.com/develop/ui/views/notifications/build-notification#progressbar
https://community.home-assistant.io/t/notification-progress-bar/695535

2024-11-10 23:04 UTC, dshokouhi commented
Thanks for the PR! Please make sure to add a beta label as features are first part of the app beta before they are released to production. You may refer to a previous PR for label format.

2024-11-11 00:09 UTC, EarMaster commented
> Thanks for the PR! Please make sure to add a beta label as features are first part of the app beta before they are released to production. You may refer to a previous PR for label format.

Added the Beta tag. I was unsure about the location tough…

2024-11-11 16:26 UTC, dshokouhi requested changes
We should mention using the `tag` parameter here as user will need to update the notification to actually track the progress.

2024-11-11 16:26 UTC, dshokouhi commented on docs/notifications/basic.md
> +The notification requires constant updates to track the progress. Once the process has completed you can remove the progress bar by sending a progress value of `-1`.
> The notification requires constant updates to track the progress

We should mention that users will want to utilize the `tag` parameter to properly update the notification. Otherwise they will end up with duplicate notifications.

![image](https://github.com/user-attachments/assets/18a2f06b-7611-4937-87a3-2e0148c30cd4)

2024-11-11 21:27 UTC, EarMaster commented on docs/notifications/basic.md
> +The notification requires constant updates to track the progress. Once the process has completed you can remove the progress bar by sending a progress value of `-1`.
I added this and linked to the #replacing section on the same page.

2024-11-12 16:21 UTC, dshokouhi approved these changes
Looks good to me, can be merged when parent is merged. Thanks for the contribution!🙏

2024-11-12 16:59 UTC, EarMaster commented
> Looks good to me, can be merged when parent is merged. Thanks for the contribution!🙏

Thank you for the quick and kind review!

2024-11-12 17:11 UTC, merged