Add android app launching links examples
home-assistant/companion.home-assistant pull request #1150
Opened 2024-12-21 00:41 UTC by GiorgioAresu

The documentation wasn't clear on how to dial a phone number (or mailto, etc.) on Android, it seemed it was only possible on iOS. I found how to do it and think it could be useful to somebody else

2025-01-31 16:52 UTC, dshokouhi requested changes
Lets reduce the amount of examples and use the current one to be more specific.

ideally the android should update to work with iOS example for the `tel` link but that would require code changes so making the current example represent what is live makes the most sense

2025-01-31 16:52 UTC, dshokouhi commented on docs/notifications/actionable.md
>    uri: "deep-link://example://link/to/content"
Lets keep this simple and just replace the current deep link example to show the `tel` example this way we cover both scenarios

2025-02-08 21:16 UTC, GiorgioAresu commented on docs/notifications/actionable.md
>    uri: "deep-link://example://link/to/content"
Done. Are you happy with the wording?

2025-02-08 22:36 UTC, dshokouhi approved these changes

2025-02-08 22:36 UTC, merged