Update meta-quest.md
home-assistant/companion.home-assistant pull request #1151
Opened 2024-12-21 15:23 UTC by slaygirlz

looks like the quest 3s wasn't added 👍

2024-12-21 16:15 UTC, jpelgrom commented on docs/meta-quest/meta-quest.md
> +| Meta Quest 3/3s | Yes |
Let's match Meta's branding

```suggestion
| Meta Quest 3/3S | Yes |
```

2024-12-27 11:26 UTC, jpelgrom requested changes
See my previous comment

2024-12-27 11:28 UTC, slaygirlz commented
sorry! I thought that maintainers can override pulls but here is the updated one

2024-12-27 13:13 UTC, jpelgrom commented
> sorry! I thought that maintainers can override pulls but here is the updated one

Yes, but you could've disagreed and it's not urgent :)

2024-12-27 13:15 UTC, jpelgrom approved these changes
Thanks!

2024-12-27 13:15 UTC, merged