Add media browser example
home-assistant/companion.home-assistant pull request #367
Opened 2020-10-15 22:54 UTC by dshokouhi

We mention `/local` but we should also mention `/media` now that we have the media browser

2020-10-16 01:53 UTC, dshokouhi commented
If an iOS team member has a moment can you please check that this works as expected? I think it will but would like to double check if we have to call this out.

2020-10-16 05:45 UTC, TomBrien commented
> If an iOS team member has a moment can you please check that this works as expected? I think it will but would like to double check if we have to call this out.

Will try to today :)

2020-10-16 08:04 UTC, TomBrien commented
I can't get it to work but I also can't get 

>Another acceptable format for the above is `/local/path/to/file.jpg`

To work. Is this meaning I should be able to have `url: "/local/some/path/to/file.jpg"` in the payload? That Doesn't seem to work on iOS. Does Android include the file (rather than just link) in the payload? I believe in iOS that we just send the source path and iOS grabs the image. So that path wouldn't work in iOS and the fact that media is protected by HA auth for `/media` is probably stopping me getting the image.

2020-10-16 14:56 UTC, dshokouhi commented
@TomBrien yea so for android what we do is we check the URL to see if its absolute or a relative path.  If it is a relative path we actually add the auth headers.  I suppose iOS does not do that yet but I thought it did.  So I assume also the Camera Proxy API does not work on iOS either?

2020-10-17 01:30 UTC, zacwest commented
Relative URLs for images should work and should provide authentication around the retrieval. I'll see if I can replicate this.

2020-11-03 22:18 UTC, TomBrien requested changes
We currently hackily use the image alt text in the CSS so need to include. Let's promote media_source harder as it's pretty assume privacy wise.

Also, I presume the OS specific bits were always supposed to be on separate lines.

2020-11-03 22:18 UTC, TomBrien commented on docs/notifications/attachments.md
>  ![](/assets/android.svg) Android users can also use `/api/camera_proxy/camera.name` where `camera.name` is replaced by the entity ID of the camera you wish to use.
```suggestion

![Android](/assets/android.svg) Android users can also use `/api/camera_proxy/camera.name` where `camera.name` is replaced by the entity ID of the camera you wish to use.
```

2020-11-03 22:18 UTC, TomBrien commented on docs/notifications/attachments.md
>  ![](/assets/apple.svg) iOS users can use the [camera stream in dynamic attachments](dynamic-content.md#camera-stream).
```suggestion

![iOS](/assets/apple.svg) iOS users can use the [camera stream in dynamic attachments](dynamic-content.md#camera-stream).
```

2020-11-03 22:18 UTC, TomBrien commented on docs/notifications/attachments.md
> +It is important to note that the attachments are required to be accessible from the internet. If you plan to use [`camera.snapshot`](https://www.home-assistant.io/integrations/camera#service-snapshot
```suggestion
It is important to note that the attachments are required to be accessible from the internet. If you plan to use [`camera.snapshot`](https://www.home-assistant.io/integrations/camera#service-snapshot), you will want to store the image in the `www` folder located in your Home Assistant [config directory](https://www.home-assistant.io/docs/configuration/). This will then expose the image to the internet so that you may use it in your notifications and receive them anywhere. The proper format for the URL is: `https://MyCustomHADomain/local/path/to/file.jpg`. Make sure to replace `MyCustomHADomain` with how you would access Home Assistant remotely in a browse, you will either use your [Nabu Casa remote URL](https://www.nabucasa.com/config/remote/) or the [base URL](https://www.home-assistant.io/integrations/http#base_url). Also, replace `path/to/file.jpg` with the actual file name and location you used in your [`camera.snapshot`](https://www.home-assistant.io/integrations/camera#service-snapshot) service call. Another acceptable format for the above is `/local/path/to/file.jpg`. 

If you are using the [`media_source` integration](https://www.home-assistant.io/integrations/media_source) you can alternatively use `/media/local/path/to/file.jpg`. Using `media_source` has the advantage that access requires authentication headers (which Home Assistant provides to the companion app). This means the content is not publicly available.
```

2020-11-03 22:19 UTC, TomBrien commented
Ok after literally years of telling people to make sure they use `default_config` turns out I didn't in production 🤦‍♂️! This works great with iOS

2020-11-03 22:34 UTC, TomBrien approved these changes
Looks good to me! Apologies again for the fail on my part 😳

2020-11-03 22:36 UTC, dshokouhi commented
@TomBrien no problem :)

2020-11-03 23:09 UTC, merged