Update siri-shortcuts.md
home-assistant/companion.home-assistant pull request #375
Opened 2020-10-27 17:00 UTC by petereit

Corrections and clarifications in steps 2-4, renumbered

2020-10-27 17:00 UTC, homeassistant commented
Hi @petereit, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;companion.home-assistant#375).

Once you do that we will be able to review and accept this pull request.

Thanks!

2020-10-27 18:08 UTC, TomBrien requested changes
This is a huge improvement. Thanks very much. Just some tiny changes that are from the original any way. Thanks again :)

2020-10-27 18:08 UTC, TomBrien commented on docs/integrations/siri-shortcuts.md
> +8. As long as the Dictionary action is above the Home Assistant action there is no need to enter anymore details. If you prefer not to use the Dictionary action, you can select "Show More" and enter
```suggestion
8. As long as the Dictionary action is above the Home Assistant action there is no need to enter anymore details. If you prefer not to use the Dictionary action, you can select "Show More" and enter the service data in JSON format in the "Service Data" field.
```

2020-10-27 18:08 UTC, TomBrien commented on docs/integrations/siri-shortcuts.md
> +6. Tap "Service" which is highlighted in "Call Service with data"
```suggestion
6. Tap "Service" which is highlighted in "Call Service with data".
```

2020-10-27 18:08 UTC, TomBrien commented on docs/integrations/siri-shortcuts.md
> +2. Tap the Plus icon at the top right to create a new shortcut
```suggestion
2. Tap the Plus icon at the top right to create a new shortcut.
```

2020-10-27 18:08 UTC, TomBrien commented on docs/integrations/siri-shortcuts.md
> +4. In the Dictionary item, tap "Add new item", tap "Text" then add `entity_id` as the key and `light.porch` as the text
```suggestion
4. In the Dictionary item, tap "Add new item", tap "Text" then add `entity_id` as the key and `light.porch` as the text.
```

2020-11-14 20:03 UTC, TomBrien approved these changes

2020-11-14 20:17 UTC, merged