Added documentation for chronometer notifications
home-assistant/companion.home-assistant pull request #386
Opened 2020-11-06 20:51 UTC by gadgetchnnel

Documentation for Chronometer notifications for PR https://github.com/home-assistant/android/pull/1154

2020-11-06 22:09 UTC, dshokouhi requested changes
We should add a beta label for all new features, we will remove them upon the next release :)

2020-11-06 22:09 UTC, dshokouhi commented on docs/notifications/basic.md
> +- when - the timestamp to count up or down to
This number is allowed to be positive or negative correct?

2020-11-06 22:09 UTC, dshokouhi commented on docs/notifications/basic.md
> +![Android](/assets/android.svg)<br />
Let's add the beta label here as its part of a new process:

```suggestion
![Android](/assets/android.svg) &nbsp;<span class="beta">BETA</span><br />
```

2020-11-06 22:23 UTC, gadgetchnnel commented on docs/notifications/basic.md
> +- when - the timestamp to count up or down to
It is a Unix timestamp (seconds since 01/01/1970). It will count down if the timestamp is in the future, or up if it is in the past.

2020-11-06 22:24 UTC, gadgetchnnel commented on docs/notifications/basic.md
> +![Android](/assets/android.svg)<br />
Just pushed an update with this.

2020-11-09 14:19 UTC, JBassett approved these changes

2020-11-09 14:33 UTC, merged