Add another example for TTS notifications
home-assistant/companion.home-assistant pull request #400
Opened 2020-11-21 16:52 UTC by Mincka

Add another example for TTS notifications to explain how to prevent notifications to be spoken based on the Ringer mode.

2020-11-21 16:53 UTC, homeassistant commented
Hi @Mincka, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;companion.home-assistant#400).

Once you do that we will be able to review and accept this pull request.

Thanks!

2020-11-21 19:07 UTC, dshokouhi requested changes
Lets just make sure we follow what's outlined in the docs and clarify to the user which sensor they should use.

2020-11-21 19:07 UTC, dshokouhi commented on docs/notifications/basic.md
> +If you do not want the TTS notification to be spoken when the Ringer mode is not `normal` (to mimic the behavior of classic notifications), you need to prevent the TTS notification to be sent in the
So we actually renamed `audio_sensor` to `ringer_mode` when we did the sensor breakup so to new users they will see `ringer_mode`. Also `audio_mode` is not the correct sensor for this as it does not relate to the actual ringer mode.

Lets also add a link to the sensor as well so they know its part of the app.  

https://companion.home-assistant.io/docs/core/sensors#audio-sensors

2020-11-22 08:04 UTC, Mincka commented on docs/notifications/basic.md
> +If you do not want the TTS notification to be spoken when the Ringer mode is not `normal` (to mimic the behavior of classic notifications), you need to prevent the TTS notification to be sent in the
Don't you think both sensors are relevant for this use case? I think it could be annoying to have the TTS speaks when the phone is ringing or even worse when you are in a call. That why using the `audio_mode` to check if the phone is "idle" (state is `normal`) makes sense to conditionally send the TTS command. That's just another idea, then people can check the documentation to understand the difference.

```suggestion
If you do not want the TTS notification to be spoken when the Ringer mode is not `normal` (to mimic the behavior of classic notifications), you need to prevent the TTS notification to be sent in the first place. This can be done by adding a condition in your automation that checks the state of the [Ringer Mode](https://companion.home-assistant.io/docs/core/sensors#audio-sensors) (`ringer_mode`). The [Audio Mode](https://companion.home-assistant.io/docs/core/sensors#audio-sensors) (`audio_mode`) can also be checked to prevent the TTS to speak when you are in a call.
```

2020-11-23 00:01 UTC, dshokouhi commented on docs/notifications/basic.md
> +If you do not want the TTS notification to be spoken when the Ringer mode is not `normal` (to mimic the behavior of classic notifications), you need to prevent the TTS notification to be sent in the
Ok makes sense :) lets just keep 1 link since it goes to the same place and drop the duplicate sensor names since it looks odd next to each other.  The audio sensors are indeed a good use here.

2020-11-23 22:16 UTC, dshokouhi approved these changes

2020-11-27 18:08 UTC, merged