Clarify map template example
home-assistant/companion.home-assistant pull request #415
Opened 2020-12-20 20:11 UTC by TomBrien

We no longer need to use the `data_template` key so ditch that confusion (child key called data too). Currently due to typing of templates, requires a work around in app which is (will be) in next  beta

Fixes #414

2020-12-20 20:24 UTC, TomBrien commented
I fully intend to submit a PR after this is merged removing this section as it's currently broken in core but can then revert that when core is fixed

2020-12-21 16:24 UTC, frenck requested changes

2020-12-21 16:24 UTC, frenck commented on docs/notifications/dynamic-content.md
> +      longitude: "{{states.device_tracker.<your_device_id_here>.attributes.longitude}}"
This is not how we should access attributes, use `state_attr()` instead.

See: <https://www.home-assistant.io/docs/configuration/templating/#states>

2020-12-21 18:38 UTC, frenck approved these changes

2020-12-21 20:05 UTC, merged