Add high accuracy mode docs
home-assistant/companion.home-assistant pull request #439
Opened 2021-01-27 20:25 UTC by chriss158

Docs about the high accuracy mode

PR here: https://github.com/home-assistant/android/pull/1321

2021-01-27 20:44 UTC, dshokouhi requested changes
Just some minor comments :)

2021-01-27 20:44 UTC, dshokouhi commented on docs/core/location.md
> +
Lets add the android logo here and a beta flag please

2021-01-27 20:44 UTC, dshokouhi commented on docs/notifications/commands.md
> +![Android](/assets/android.svg)
Lets include a beta flag here as well since it wont be released just  yet once merged

2021-01-27 20:44 UTC, dshokouhi commented on docs/core/location.md
> +If the high accuracy mode is enabled, you will see a notification with details about the location. This notification is permanent duo to requirements of the android system. But you can hide/minimize
```suggestion
If the high accuracy mode is enabled, you will see a notification with details about the location. This notification is permanent due to requirements of the android system. But you can hide/minimize the location notification via notification settings of your system.
```

2021-01-27 20:45 UTC, dshokouhi commented
side note: I need to remove the older beta flags in a future PR since we cut a release recently lol 🙈

2021-01-27 20:57 UTC, chriss158 commented
lol yeah the bluetooth beta flag is still there ^^

Thanks for review

2021-01-27 22:06 UTC, dshokouhi approved these changes
Looks good to me, unless someone else see's we need another change we can merge after the parent is merged. 👍

2021-01-28 21:01 UTC, JBassett approved these changes

2021-01-28 21:01 UTC, merged