Add docs for command navigate
home-assistant/companion.home-assistant pull request #442
Opened 2021-01-28 05:47 UTC by dshokouhi

Docs for: https://github.com/home-assistant/android/pull/1327

2021-01-28 11:19 UTC, TomBrien commented on docs/notifications/commands.md
> +  - alias: Notify Mobile app
```suggestion
  - alias: Mobile App Launch Navigate
```

2021-01-28 11:20 UTC, TomBrien requested changes
Just a super minor think, we should aim to keep the `alias`s unique I think

2021-01-28 19:54 UTC, dshokouhi commented
> Just a super minor think, we should aim to keep the `alias`s unique I think

yea we got a few places to clean that up :)

2021-01-28 20:03 UTC, TomBrien approved these changes
All good by me

2021-01-28 22:06 UTC, dshokouhi commented
Made some changes to reflect on the more generic approach here so had to shuffle it around.

2021-01-29 12:57 UTC, JBassett requested changes

2021-01-29 12:57 UTC, JBassett commented on docs/notifications/commands.md
> +        message: "command_navigate"
```suggestion
        message: "command_activity"
```

2021-01-29 12:57 UTC, JBassett commented on docs/notifications/commands.md
> +        message: "command_navigate"
```suggestion
        message: "command_activity"
```

2021-01-29 13:11 UTC, merged