Update android-power-menu.md
home-assistant/companion.home-assistant pull request #557
Opened 2021-07-20 02:04 UTC by B-Kramer

These controls moved in android 12 beta.

2021-07-20 02:04 UTC, homeassistant commented
Hi @B-Kramer, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;companion.home-assistant#557).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-07-20 14:03 UTC, dshokouhi requested changes
I was hoping to find a better google support link instead of linking to a blog post from an android fan site. Maybe once Android 12 is released Google will have official documentation on this.

2021-07-20 14:03 UTC, dshokouhi commented on docs/integrations/android-power-menu.md
> +NOTE: The Android power menu controls were moved in Android 12 Beta.  If your phone is running Android 12 or newer, the controls can now be accessed from the quick settings by [pulling down on the st
Lets make sure to follow the docusaurus special `note` blocks so it can match the other notes that we have

```suggestion
:::info
The Android power menu controls were moved in Android 12 Beta.  If your phone is running Android 12 or newer, the controls can now be accessed from the quick settings by [pulling down on the status bar.](https://9to5google.com/2021/06/09/android-12-beta-2-quick-settings-google-pay-home-controls-power/)
:::
```

2021-07-22 03:44 UTC, B-Kramer commented
> I was hoping to find a better google support link instead of linking to a blog post from an android fan site. Maybe once Android 12 is released Google will have official documentation on this.

Yeah, fair enough.  I ran into it and it took a minute to find the controls, so I thought I'd throw it out there.  Nothing on the Android site that I've seen yet, maybe waiting until release is a good idea.

2022-01-28 17:31 UTC, dshokouhi commented
@B-Kramer were you planning on moving forward with this PR?

2022-01-28 17:38 UTC, B-Kramer commented
Yeah we can merge it, I think.  Still never found the updated google reference page though.

2022-01-28 17:39 UTC, dshokouhi approved these changes

2022-01-28 17:39 UTC, merged