Some Hass.io -> Home Assistant updates
home-assistant/companion.home-assistant pull request #561
Opened 2021-07-21 11:10 UTC by TomBrien

Update references to Hass.io

2021-07-26 12:55 UTC, schmjop requested changes
Replace remaining occurence of hassio.local

2021-07-26 12:55 UTC, schmjop commented on docs/troubleshooting/networking.md
>  If you don't want to use Nabu Casa Cloud (which is fine, but you should still subscribe and enjoy the warm feeling of supporting Home Assistant), you need HA to be accessible from the internet. This
Replace remaining occurence of hassio.local
```suggestion
If you don't want to use Nabu Casa Cloud (which is fine, but you should still subscribe and enjoy the warm feeling of supporting Home Assistant), you need HA to be accessible from the internet. This requires opening a port on your router and getting a name for your Home Assistant on the internet. While it is possible to have your HA use Port 8123 internally and have your router do a port-forwarding from say the default https port of 443 to 8123, we recommend you NOT do this for reasons of simplicity which we will explain later. You also need a name for your Home Assistant as homeassistant.local is a private domain suffix that does not exist on the internet.

```

2021-07-26 12:59 UTC, TomBrien commented on docs/troubleshooting/networking.md
>  If you don't want to use Nabu Casa Cloud (which is fine, but you should still subscribe and enjoy the warm feeling of supporting Home Assistant), you need HA to be accessible from the internet. This
Nice spot cheers

2021-07-28 03:41 UTC, zacwest approved these changes

2021-07-28 06:15 UTC, frenck approved these changes
LGTM, thanks 👍

2021-07-28 06:15 UTC, merged