Include URLSessionTask in errors.md
home-assistant/companion.home-assistant pull request #562
Opened 2021-07-25 13:36 UTC by schmjop

Update of errors.md based on [issue 1571](https://github.com/home-assistant/iOS/issues/1571) in the Home Assistant iOS repo.

2021-07-25 15:29 UTC, TomBrien requested changes
Just a few tweaks to wordings

2021-07-25 15:29 UTC, TomBrien commented on docs/troubleshooting/errors.md
> +### "URLSessionTask failed with error"
```suggestion
### URLSessionTask failed with error
```

2021-07-25 15:29 UTC, TomBrien commented on docs/troubleshooting/errors.md
> +*   You have configured an incorrect `external url` in your `configuration.yaml` file. E.g. when forwarding external port 443 to internal port 8123 in your router settings, you don't have to add a po
```suggestion
*   You have configured an incorrect external url in your instance. E.g. when forwarding external port 443 to your instance's port (normally 8123), you don't have to append a port to your URL.
```

You can configure the URL setting through either YAML or the UI.

2021-07-25 17:34 UTC, schmjop commented on docs/troubleshooting/errors.md
> +*   You have configured an incorrect `external url` in your `configuration.yaml` file. E.g. when forwarding external port 443 to internal port 8123 in your router settings, you don't have to add a po
Thanks!

2021-07-26 12:16 UTC, TomBrien commented
@schmjop if you're happy with the suggestions, can you please click "Apply Suggestion" under each (you may need to unresolve the comments first). Otherwise let me know and we can discuss what might be best.

2021-07-26 12:36 UTC, schmjop commented
My bad, I have merged your requested changes. Thanks for having a look!

2021-07-26 12:37 UTC, TomBrien commented
Great, cheers

2021-07-26 12:37 UTC, merged