Update networking.md
home-assistant/companion.home-assistant pull request #636
Opened 2021-12-18 18:22 UTC by mircoboschi

Added brief documentation for TLS Client Certificate PR

2021-12-18 18:22 UTC, homeassistant commented
Hi @mircoboschi, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;companion.home-assistant#636).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-12-18 18:42 UTC, dshokouhi requested changes
Just a few comments

2021-12-18 18:42 UTC, dshokouhi commented on docs/troubleshooting/networking.md
> +## Addendum: TLS Client Certificates (MTLS)
Lets add the android logo and BETA flag here so user know they need to be on the beta version of the android app. You can see an example on the Wear OS page.

2021-12-18 18:42 UTC, dshokouhi commented on docs/troubleshooting/networking.md
> +- Copy client certificate key in internal memory -> `Android/data/io.homeassistant.companion.android/files` and rename it to `tls_client.key`
Do we think its worth mentioning how to copy the files here? Also the example should also mention that minimal app users will have a slightly different location because the package name will be `io.homeassistant.companion.android.minimal`

2021-12-18 19:12 UTC, mircoboschi commented on docs/troubleshooting/networking.md
> +- Copy client certificate key in internal memory -> `Android/data/io.homeassistant.companion.android/files` and rename it to `tls_client.key`
I've written instruction there because, right now, there is not UI code that helps user to pick these files.
Thanks for minimal and other package type mention, i'll correct that.
The whole thing will be changed if we implement a different key load method.

2021-12-18 19:23 UTC, mircoboschi commented on docs/troubleshooting/networking.md
> +## Addendum: TLS Client Certificates (MTLS)
Done

2021-12-18 19:24 UTC, mircoboschi commented on docs/troubleshooting/networking.md
> +- Copy client certificate key in internal memory -> `Android/data/io.homeassistant.companion.android/files` and rename it to `tls_client.key`
Added some details as per you suggestions

2021-12-19 01:03 UTC, dshokouhi approved these changes
Looks good to me, can be merged after the parent PR is merged

2022-01-02 17:12 UTC, TomBrien commented on docs/troubleshooting/networking.md
> +## Addendum: TLS Client Certificates (MTLS)
```suggestion
## Client Certificates
```
Let's keep this header generic so we can add other details in here later without changing the header and this breaking direct links. I also think this would be better above the addenda

2022-06-30 20:15 UTC, dshokouhi commented
Closing as the parent PR has been closed, this is also superseded by #748

2022-06-30 20:15 UTC, closed without merging