Add pinch-to-zoom
home-assistant/companion.home-assistant pull request #683
Opened 2022-02-09 17:35 UTC by micronen

2022-02-09 17:35 UTC, homeassistant commented
Hi @micronen, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;companion.home-assistant#683).

Once you do that we will be able to review and accept this pull request.

Thanks!

2022-02-09 18:16 UTC, dshokouhi requested changes
Just needs to be marked as a beta feature

2022-02-09 18:16 UTC, dshokouhi commented on docs/integrations/android-webview.md
> +The ![Android](/assets/android.svg) Android app has the ability to enable Pinch-To-Zoom to allow multi-touch zoom by enabling corresponding setting in Companion App Configuration.
Can you please add a beta label next to the Android logo? You can reference a recent PR for an example of the tag to use.

2022-02-15 19:47 UTC, dshokouhi commented on docs/integrations/android-webview.md
> +The ![Android](/assets/android.svg) Android app has the ability to enable Pinch-To-Zoom to allow multi-touch zoom by enabling corresponding setting in Companion App Configuration.
@micronen just a FYI we need to add the beta tag here in case you missed this notification :)

2022-02-15 22:30 UTC, micronen commented on docs/integrations/android-webview.md
> +The ![Android](/assets/android.svg) Android app has the ability to enable Pinch-To-Zoom to allow multi-touch zoom by enabling corresponding setting in Companion App Configuration.
Added beta tag, as found elsewhere in the docs

2022-02-15 22:31 UTC, dshokouhi approved these changes
Looks good to me, can be merged once parent is merged

2022-02-17 03:31 UTC, merged