Update docs for supporting video attachment for notifications on Android
home-assistant/companion.home-assistant pull request #705
Opened 2022-03-05 00:49 UTC by NickM-27

2022-03-05 01:07 UTC, dshokouhi requested changes
Just a couple minor comments, for the beta flag you can refer to a recent android PR to see how to add it.  When we cut a release we will remove the tag later.

2022-03-05 01:07 UTC, dshokouhi commented on docs/notifications/attachments.md
> +|   Video   | 50 MB   | MPEG, MPEG2, MPEG4, AVI   | ![Android](/assets/android.svg) Android & ![iOS](/assets/iOS.svg) |
We need to add a beta flag here to indicate this feature is only available in the beta.

2022-03-05 01:07 UTC, dshokouhi commented on docs/notifications/attachments.md
> +*   If you are setting the `image`] and `video` property then only the video will be displayed on the device.
looks like a stray `]` 🙂

2022-03-05 01:21 UTC, dshokouhi commented
Also could you update the feature table at https://companion.home-assistant.io/docs/core/ we can now include check marks for both android versions!

2022-03-05 01:22 UTC, NickM-27 commented on docs/notifications/attachments.md
> +|   Video   | 50 MB   | MPEG, MPEG2, MPEG4, AVI   | ![Android](/assets/android.svg) Android & ![iOS](/assets/iOS.svg) |
Do you want the beta tag to go after the android icon?

2022-03-05 01:24 UTC, dshokouhi commented on docs/notifications/attachments.md
> +|   Video   | 50 MB   | MPEG, MPEG2, MPEG4, AVI   | ![Android](/assets/android.svg) Android & ![iOS](/assets/iOS.svg) |
yea that would look better i think :)

2022-03-05 01:34 UTC, dshokouhi approved these changes
We don't really need the `br` tag with the beta in this spot but it doesnt hurt the design, feel free to remove that if you want

2022-03-05 01:42 UTC, NickM-27 commented
> We don't really need the `br` tag with the beta in this spot but it doesnt hurt the design, feel free to remove that if you want

Removed it 👍

2022-03-08 02:44 UTC, JBassett approved these changes

2022-03-08 02:44 UTC, merged