Updated actionable notifications documentation
home-assistant/companion.home-assistant pull request #708
Opened 2022-03-08 08:57 UTC by tamueller

Added further considerations on blocking behaviour
(as discussed in https://github.com/home-assistant/companion.home-assistant/issues/701)

2022-03-08 08:57 UTC, homeassistant commented
Hi @tamueller, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;companion.home-assistant#708).

Once you do that we will be able to review and accept this pull request.

Thanks!

2022-03-11 15:54 UTC, dshokouhi requested changes
Just some minor comments to fix.

I do wonder though if we should place the last 2 options first because those options will work for iOS and Android while the first option is Android only.

2022-03-11 15:54 UTC, dshokouhi commented on docs/notifications/actionable.md
> +-   In Android you can listen to the event that is fired when the notification is closed, and handle it accordingly. This can be achieved by adding the following lines
Lets also link to the docs page here as it explains the cleared event in more detail: https://companion.home-assistant.io/docs/notifications/notification-cleared

2022-03-11 15:54 UTC, dshokouhi commented on docs/notifications/actionable.md
> +-   It is possible to [clear notifications](https://companion.home-assistant.io/docs/notifications/notifications-basic#clearing) which can bei combined with timeouts and parallel execution mode to ac
Typo here :)

2022-03-11 16:19 UTC, tamueller commented
@dshokouhi Hi Daniel, thanks for looking at the PR. I incorporated your comments and created another commit. As far as I understand github I do not need to create another PR, as the PR now contains both commits, right?

2022-03-11 16:25 UTC, dshokouhi approved these changes
Looks good to me, lets wait a day or 2 to see if the iOS team has anything to add :) Thanks for the update!

2022-03-11 16:38 UTC, zacwest approved these changes

2022-03-11 16:39 UTC, merged