Add Beacon Monitor Docs
home-assistant/companion.home-assistant pull request #736
Opened 2022-04-24 18:44 UTC by Adi146

2022-04-24 23:03 UTC, dshokouhi requested changes
Just need to add the beta tags in a couple places

2022-04-24 23:03 UTC, dshokouhi commented on docs/core/sensors.md
> +![Android](/assets/android.svg)
Please add a beta tag as well so users know the feature is in the beta version of the app

2022-04-24 23:03 UTC, dshokouhi commented on docs/notifications/commands.md
> +![Android](/assets/android.svg)
Let's add a beta tag here as well since this will be in the beta first

2022-04-25 20:56 UTC, dshokouhi commented on docs/notifications/commands.md
> +| `command_beacon_monitor` | Trun Beacon Monitoring on or off. |
```suggestion
| `command_beacon_monitor` | Turn Beacon Monitoring on or off. |
```

2022-04-27 17:08 UTC, dshokouhi approved these changes
Looks good to me, can be merged when parent is merged

2022-09-05 14:09 UTC, JBassett approved these changes

2022-09-05 14:09 UTC, JBassett commented
@Adi146 Just need to fix merge conflicts

2022-09-05 14:24 UTC, jpelgrom commented
By now the format has also changed to use `command` instead of `title` for notification commands, so not just a merge conflict to resolve.

2022-09-05 15:36 UTC, dshokouhi commented
> By now the format has also changed to use `command` instead of `title` for notification commands, so not just a merge conflict to resolve.

Good catch totally missed that in my last review

2022-09-05 17:22 UTC, dshokouhi requested changes
Just a small update for the notification command format

2022-09-05 17:22 UTC, dshokouhi commented on docs/notifications/commands.md
> +You can turn the Beacon Monitor on or off using `message: command_beacon_monitor` with the `title` being either `turn_off` or `turn_on`. If `title` is blank, not set or not one of the above expected
We need to update the format to reflect `command` in place of `title`

2022-09-05 17:22 UTC, dshokouhi commented on docs/notifications/commands.md
> +          title: "turn_off"
```suggestion
          data:
            command: "turn_off"
```

Lets update this format to match what is actually expected

2022-09-05 19:49 UTC, Adi146 commented
I adjusted the docs, please let me know If I missed something

2022-09-05 19:53 UTC, dshokouhi approved these changes

2022-09-05 19:53 UTC, merged