Add app lock notify commands
home-assistant/companion.home-assistant pull request #809
Opened 2022-09-08 17:56 UTC by RoboMagus

For PR home-assistant/android#2868

2022-09-08 18:00 UTC, dshokouhi commented
Lets make sure to add the beta flag to the table and the actual description so users know its part of the beta

2022-09-08 22:10 UTC, dshokouhi requested changes
Missing the beta flag `<span class='beta'>BETA</span>` in the table and description. As features get merged they are first part of the beta until a release is cut.

2022-09-13 15:04 UTC, dshokouhi commented on docs/notifications/commands.md
> +| `app_lock_enabled` | boolean | Wether the biometric / screenlock will be enabled |
```suggestion
| `app_lock_enabled` | boolean | Whether the biometric / screen lock will be enabled |
```

2022-09-13 15:04 UTC, dshokouhi commented on docs/notifications/commands.md
> +| `home_bypass_enabled` | boolean | Wether the lock is bypassed when connected to home WiFi |
```suggestion
| `home_bypass_enabled` | boolean | Whether the lock is bypassed when connected to home WiFi |
```

2022-09-13 15:04 UTC, dshokouhi commented
2 small typos, sorry for not catching that earlier :)

2022-09-13 16:19 UTC, RoboMagus commented
Np, thanks for being so active in guiding the development!

2022-09-13 16:24 UTC, dshokouhi approved these changes
Looks good to me can be merged when the parent is merged

2022-10-02 18:06 UTC, dshokouhi commented
@RoboMagus  just a FYI but there is a conflict in this file now

2022-10-19 18:46 UTC, merged