Docs for Beacon Monitor UUID filter
home-assistant/companion.home-assistant pull request #876
Opened 2022-12-28 14:54 UTC by chatziko

Document newly added settings in Beacon Monitor.
home-assistant/android#3178

2022-12-28 19:19 UTC, dshokouhi requested changes
Thanks for your contribution! We actually need to separate this new sentence and make sure to mark with a beta label so users know the feature is in the beta version of the app. Once a new release is cut we will remove the beta labels.

2022-12-29 09:51 UTC, chatziko commented
> We actually need to separate this new sentence and make sure to mark with a beta label so users know the feature is in the beta version of the app. Once a new release is cut we will remove the beta labels.

Thanks for the feedback, I just did this (not sure about the exact style, I copied it from another PR).

2022-12-29 23:24 UTC, dshokouhi approved these changes
Looks good to me, can be merged when the parent is merged.

2023-01-11 21:37 UTC, JBassett approved these changes

2023-01-13 16:06 UTC, merged