Add ssl error from weird misconfig relating to nabucasa cloud
home-assistant/companion.home-assistant pull request #886
Opened 2023-01-16 10:33 UTC by spookyuser

2023-01-17 18:45 UTC, dshokouhi requested changes
Thanks for the PR! Just a small suggestion as we should make sure to capitalize the company name and we also do not need to link to a community post, just mentioning the issue and fix is good enough :)

2023-01-17 18:45 UTC, dshokouhi commented on docs/troubleshooting/errors.md
> +* You are logged into nabu casa cloud without a subscription and trying to access your instance with a reverse proxy. [Just log out from your nabu casa cloud account.](https://community.home-assistan
```suggestion
* You are logged into Nabu Casa cloud without a subscription and trying to access your instance with a reverse proxy. Just log out from your Nabu Casa cloud account.
```

2023-01-18 08:38 UTC, spookyuser commented
Awesome, np!

2023-01-22 17:50 UTC, dshokouhi approved these changes
Thank you!

2023-01-22 17:50 UTC, merged