CarPlay documentation
home-assistant/companion.home-assistant pull request #923
Opened 2023-03-09 17:52 UTC by LuisFALopes

Added CarPlay documentation

2023-03-09 18:31 UTC, dshokouhi commented
Nice to see this! I would say lets also add it to the home page to highlight it more :)

2023-03-09 20:45 UTC, TomBrien requested changes
Looks great and amazing work getting this developed! Just some very small changes to be consistent with the style standards used elsewhere. 

I think this feature, when released fully, will merit a blog post on the main website too.

2023-03-09 20:45 UTC, TomBrien commented on docs/carplay/carplay.md
> +Home Assistant has started to offer an CarPlay experience.  This will allow you to interact with various entities safely while driving your vehicle.
```suggestion
Home Assistant offers a CarPlay experience. This will allow you to interact with various entities safely while driving your vehicle.
```

We should keep the language generic and just document what can be done rather than promoting as new. A blog post on the main site can present that this is new.

2023-03-09 20:45 UTC, TomBrien commented on docs/carplay/carplay.md
> +In order to use this integration you will need an iPhone as well as a vehicles head unit that supports CarPlay.  Once you are signed in with your iPhone, you should be all set to use the Home Assista
```suggestion
In order to use this integration you will need an iPhone as well as a vehicle with a head unit that supports CarPlay. Once you are signed in with your iPhone, you should be all set to use the Home Assistant icon on the CarPlay home screen.
```

2023-03-10 10:21 UTC, LuisFALopes commented
@TomBrien Thank you for your suggestion!  I also agree with a blog post on the main website.

2023-03-10 10:37 UTC, TomBrien approved these changes
Thanks. This looks good and can be merged once the home-assistant/iOS#2320 is merged.

2024-06-10 07:58 UTC, bgoncal commented
I just reviewed and updated the doc and it should be good to merge in my opinion @TomBrien @frenck

2024-06-11 08:19 UTC, merged