add android auto carinfo documentation
home-assistant/companion.home-assistant pull request #936
Opened 2023-04-09 17:48 UTC by drosoCode

Add Android Auto CarInfo sensors documentation

Android PR: https://github.com/home-assistant/android/pull/3399

2023-04-09 17:52 UTC, dshokouhi commented
Please also add the beta label to the new sensors so users can distinguish between what is in production and the beta version.

2023-07-13 22:59 UTC, dshokouhi commented on docs/core/sensors.md
> + Note that you need to start the Home-Assistant app on your Android Auto screen each time that you connect the phone to the car to allow these sensors to work (once started, you can dismiss the app).
May want to fix this paragraph to mention the new `car_ui` parameter :)

2023-07-13 22:59 UTC, dshokouhi commented on docs/core/sensors.md
> +| `android_auto_odometer` | <span class='beta'>BETA</span> The the value of the car odometer in meters |
We should update the sensor names to match the latest PR changes

2023-07-13 23:00 UTC, dshokouhi requested changes
Thanks for adding the beta label. Just a couple comments to bring the docs up to line with current features and latest PR changes. Also need to resolve the conflict in the sensors file.

2023-07-15 15:49 UTC, dshokouhi approved these changes
Looks good to me, can be merged when parent is merged

2023-07-15 17:17 UTC, jpelgrom reviewed
Should this be referred to on the Android Auto page as well?

2023-07-15 17:17 UTC, jpelgrom commented on docs/core/sensors.md
> + To make things easier, you may want to use the [`car_ui` parameter](../android-auto/android-auto.md#notifications) to show a notification on your car when you [connect your phone](./sensors.md#andro
Did you want a visible line break/two paragraphs here? If so you need to keep one line empty. Currently it is one paragraph.

2023-07-15 17:17 UTC, jpelgrom commented on docs/core/sensors.md
> +|| Sensor | Description |
Typo results in the first column having no title, second column titled Sensor, and Description being dropped from the table

```suggestion
| Sensor | Description |
```

2023-07-17 12:05 UTC, merged