Update outdated parts of documentation about Actions
home-assistant/companion.home-assistant pull request #945
Opened 2023-05-24 18:56 UTC by romanr

Fix outdated links and instructions to reflect current iOS and Companion app.

2023-05-25 01:35 UTC, TomBrien requested changes

2023-05-25 01:35 UTC, TomBrien commented on docs/core/actions.md
> +[Home Screen Quick Actions](https://support.apple.com/en-au/guide/iphone/iphcc8f419db/ios) provides a convenient shortcut to your actions and is accessed by Force Touching the Home Assistant companio
```suggestion
[Home Screen Quick Actions](https://support.apple.com/guide/iphone/iphcc8f419db/ios) provides a convenient shortcut to your actions and is accessed by touching and holding the Home Assistant companion app icon on your home screen.
```
It's best to use non-region specific link. The branding of force vs haptic vs 3D Touch interaction seems rather unclear/confused. So I think it's best to follow the terminology used be Apple in the link you provided.

2023-05-25 18:09 UTC, romanr commented on docs/core/actions.md
> +Actions are created only in Companion App on iOS. Navigate to `Settings` > `Companion App` > `Actions section`. Each action has required fields depending on your device:
The Home assistant link was removed because it does not lead to a relevant place. Common use case is when documentation is read on desktop and actions performed on mobile.    
Yes, the wording was changed because it was difficult to comprehend and required multiple readings for newcomer to understand. There are multiple questions in forums asking how to find this functionality because documentation is not clear enough about the subject.

2023-05-25 18:11 UTC, romanr commented on docs/core/actions.md
> +[Home Screen Quick Actions](https://support.apple.com/en-au/guide/iphone/iphcc8f419db/ios) provides a convenient shortcut to your actions and is accessed by Force Touching the Home Assistant companio
Your'e right, looks looks Apple moved away from "Force touch" nomenclature.

2024-06-09 11:33 UTC, frenck commented
Because there hasn't been any activity on this PR for quite some time now, I've decided to close it for being stale.

Feel free to re-open this PR when you are ready to pick up work on it again 👍

../Frenck

2024-06-09 11:33 UTC, closed without merging